### PR TITLE
Some minor bugfixes

### PR DESCRIPTION
**Pull request by athiele**
Here are some fixes of bugs that occurred in productive use of this cookbook.

HTH

### CODE REVIEW

**Comment by andruby** [comment]
Hey athiele,

I'm refactoring the recipes to make them clearer and to make this cookbook more flexible. The work is almost done and lives in #7. Platform specific code has their own recipes.

Do we want to force all redhat users to compile git from source? You could split & squash this PR into 2 PR's: git::source and init file fix. I'd merge the init fix right away.

**Comment by athiele** [comment]
Refactoring seems to be a very nice idea. Compiling git from source is important, because some features of gitlab need a version > 1.7.4 for example showing commit data beneath the files. Otherwise there is an endless "loading" loop ...

**Comment by andruby** [comment]
That's a good reason! Let's offer users of the cookbook a choice with an attribute `node['git']['origin']`:
- `source` (default): compile latest version from source.
- `package`: so users of newer distro's can use updated package managers.
- `manual`: stay out of their way and let them do it.

**Comment by athiele** [comment]
Sounds good. We can set source as default for RHELoid but package as default for the cool OSes :)

**Pull request closed without merging**
