### PR TITLE
'80' is the port used by default but it's possible configuring it.

### PR DESCRIPTION
**Pull request by tnarik**
Hi Andy,

I made the gitlabhq port configurable (by default it would be '80' and '443' if SSL).
Also, the disabling of the default nginx site have been modified to use the nginx cookbook method:

```
nginx_site 'default' do
  enable false
end
```

Most probably this should be made optional if there is a  port conflict, and otherwise rely on the nginx cookbook itself to disable the default it that's what someone really wants (in my setup I'm already disabling the default site, for instance).

### CODE REVIEW

**Comment by andruby** [comment]
Looks good tnarik!

**Comment by andruby** [comment]
Actually, could you rename the `['gitlab']['port']` attribute to `['gitlab']['http_port']` and add `['gitlab']['https_port']` with default 443 so that number is also no longer hardcoded?

**Comment by tnarik** [comment]
Sure, let me add that and test it.

**Comment by tnarik** [comment]
Hi Andy,

I remerged to your HEAD while adding the `http_port` and `https_port` changes, as well as some other modifications such as:
- Using the latest init script
- Adding the group and user to the resources where missing to ensure files belong to `git:git`  (or the configured user and group).
- got gitlab-shell to install in the correct order (not at the end of the Chef run)
- modified `/home/git/repositories` permissions so that `rake gitlab:check` succeeds.
- made sure the configurable ports are used for nginx and gitlab-shell.

I have one suggestion (I checked the code you use to select between the cookbook execution and the development mode. It looks a bit redundant having three different settings for this, namely `rails_env`, `bundle_install_cmd` and `sync_repository`, because you need to change the three of them, while before you only needed to change the `rails_env` setting.

Anyway, there you go. And thanks for providing us with a good base cookbook to deploy `gitlab` with.

**Comment by andruby** [comment]
Tnarik, that's awesome! I'm merging.

Regarding to your last suggestion: you are right, it is a bit of duplication. But I'm actually going to create a separate "development" recipe which contains all the development only logic. This way the default recipe is a cleaner production only recipe.

**Pull request merged**
