### PR TITLE
5.3 update

### PR DESCRIPTION
**Pull request by athiele**
Hi Andrew,

I just merged the 5.3 update of the @martinlauer fork to give it a try on Centos. It works.

### CODE REVIEW

**Comment by andruby** [comment]
Cool. Martin should have made a Pull Request so we could have merged these changes piece by piece.
The refactors I've done however seem to interfere with the code from you guys..

I've been using test-kitchen in another cookbook and want to add that ASAP. So we can have make sure we don't break the cookbook for each other's platform :)

**Comment by martinlauer** [comment]
Sorry guys im pretty new into github and a deadline at work left no spare time to finalize the cookbook. ;)

**Comment by andruby** [comment]
No worries Martin. I've been neglecting this cookbook due to work deadlines as well. Thanks for your contribution, it's clean code that I would love to merge in. When I get the time I might do just that.

**Comment by athiele** [comment]
Alright, I will leave this pull request open as a placeholder / reminder for the 5.3 upgrade if you dont mind.

**Pull request closed without merging**
